server:
  port: 8090

spring:
  application:
    name: "loans"

  profiles:
    active: "prod"

  datasource:
    url: jdbc:postgresql://microservices-db.c5gj6mqae4k3.ap-south-1.rds.amazonaws.com:5432/loans_db
    username: postgres
    password: tarunkumar
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: "optional:configserver:http://configserver.bank.local:8071/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: unrestricted
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eurekaserver.bank.local:8761/eureka/

info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"

logging:
  level:
    com:
      eazybytes:
        loans: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"